### ISSUE TITLE
Link buttons not working

### ISSUE THREAD

**Issue by panpansh** [paigen11/mysql-registration-passport#1]
I can use api from client using routes inside browser '/login' by example but using buttons not working

**Comment by paigen11** [comment]
I'm not sure what to tell you, the buttons and routes work fine on my version. I used `docker-compose build` then `docker-compose up` to spin up all of the apps and the databases and they work fine. Have you `git pull`ed in the lastest version of the repo and tried to rerun it?

**Comment by paigen11** [comment]
Closing this as a non-issue

**Comment by thomassb** [comment]
#10 Issue fix here.
