### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by thomassb** [paigen11/mysql-registration-passport#10]
Linkbutton do not work in the correct mannor.
Button text is linked however the button click event does nothing.
Suggested fix: components/LinkButtons.js
`      <Link style={linkStyle} to={link}>    
        <Button variant="contained" color="primary" style={buttonStyle}>
            {buttonText}
        </Button>
        </Link>`

Sorry my laptop is being daft and submitted this before I was ready

**Comment by paigen11** [comment]
Thanks for the suggested change, I'm making it now and pushing the change into master. I appreciate it!
