### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [paigen11/mysql-registration-passport#14]
Problem 1 - Follow parent directory instruction
1. Git Clone ...
2. Pre-installed Docker and running.
3. docker-compose build
4. docker-compose up
5. From the unix-terminal, copy http://localhost:3000/ or http://172.18.0.4:3000/
6. The page on the browser is spinning continuously.
 
Problem 2 - Follow Client folder instruction

7. Go to client folder, do npm install and npm start, as instructed from Unix-Terminal, copy http://localhost:3000/ 
8. Go to localhost:3000 and able to see the website.
9. Register or login, 
Got this error: 
"Unhandled Rejection (TypeError): Cannot read property 'data' of undefined"
Note: I've got this error even when the Docker is not running but have Express server running. 

10. Docker and Client Server points me to use localhost:3000. 

Problem 3:
If I start the client server, do I need to start the API server as well?

Suggestion:
I need a clearer instruction to get started. There are two sets of instructions, one on the parent directory and another one on the client directory. I don't know which one to follow.  
Wonderful project!!

**Comment by paigen11** [comment]
Sorry, I only now saw this. Follow the instructions in the README.md at the root of the project, the instructions I wrote, not the ones that automatically come with create-react-app in the client folder.

After `docker-compose up` runs and shows the database, server and client applications are successfully spun up, go to `http://localhost:3031`to get to the home screen. Inside the Docker container the client app is running on port 3000, but to access the site externally, it's being proxied to port 3031.

You can see the ports for the client and api folder inside the `docker-compose.yml` file. And you can also see the client depends on the api, the api depends on the db. So without both of those running, the client server container will not start up successfully.

I hope this helps.
